#!/usr/bin/env python3
"""
Journal Square market pipeline — database layer.

Append-only time-series of apartment availability for the Journal Square comp set.
One row per (snapshot_date x building x unit). Each refresh appends a new dated
snapshot, so history accumulates: rent trends, concession timelines, days-on-market.

CLI:
    python pipeline.py init                 # create the database + schema
    python pipeline.py seed                 # (re)load building dimension from config
    python pipeline.py ingest <file.json>   # append a snapshot of unit rows
    python pipeline.py export                # write dashboard_data.json from the DB
    python pipeline.py status                # show what's in the DB

The scraper (scrape.py) calls ingest_snapshot() with the units it pulls.
The dashboard reads dashboard_data.json (regenerated by `export`).
"""
import sqlite3, json, sys, os, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
import physical_store as PS
import paths

# --- Eastern-time clock: the market (and the study's "as-of" date) lives in ET.
# CI runners are UTC, so date.today() rolls over ~5 hours early and stamps a
# future date on evening runs (observed 2026-06-11 -> '2026-06-12'). All
# snapshot/as-of dates use ET; precise instants (generated_at) stay UTC.
try:
    from zoneinfo import ZoneInfo
    _ET = ZoneInfo("America/New_York")
except Exception:
    _ET = datetime.timezone(datetime.timedelta(hours=-5))

def today_et():
    return datetime.datetime.now(_ET).date().isoformat()

def now_et():
    return datetime.datetime.now(_ET).isoformat(timespec="seconds")
DB_PATH      = paths.db_path()
CONFIG_PATH  = paths.config_path("availability_sources.json")
META_PATH    = paths.config_path("buildings_meta.json")
EXPORT_PATH  = paths.data_path("dashboard_data.json")

SCHEMA = """
CREATE TABLE IF NOT EXISTS buildings (
    id          TEXT PRIMARY KEY,      -- slug, e.g. 'urby'
    name        TEXT NOT NULL,         -- display name (matches registry)
    units       INTEGER,               -- total units in the building
    year_built  INTEGER,
    stories     INTEGER,
    mgmt        TEXT,
    in_market   INTEGER DEFAULT 1,     -- 1/0: include in market averages
    source_url  TEXT,                  -- availability page
    method      TEXT,                  -- dom_read | portal | network_api
    portal_url  TEXT,
    api_endpoint TEXT,
    js_rendered INTEGER,
    notes       TEXT,
    added_at    TEXT
);

-- One row per scrape run per building (monitoring + current concession).
CREATE TABLE IF NOT EXISTS snapshots (
    snapshot_date   TEXT NOT NULL,     -- YYYY-MM-DD
    building_id     TEXT NOT NULL,
    units_captured  INTEGER,
    status          TEXT,              -- working | stub_no_data | error
    concession_text TEXT,
    concession_pct  REAL,              -- effective discount, 0..1
    ran_at          TEXT,
    message         TEXT,
    PRIMARY KEY (snapshot_date, building_id),
    FOREIGN KEY (building_id) REFERENCES buildings(id)
);

-- The fact table: one row per available unit per pull date.
CREATE TABLE IF NOT EXISTS listings (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    snapshot_date       TEXT NOT NULL,
    building_id         TEXT NOT NULL,
    unit                TEXT,          -- residence/unit no. if published
    unit_type           TEXT,          -- Studio | 1BR | 2BR | 3BR
    beds                INTEGER,
    baths               REAL,
    sqft                INTEGER,       -- null if not published (sf_policy)
    asking_rent         REAL,          -- gross asking
    net_effective_rent  REAL,          -- after concession
    price_basis         TEXT,          -- 'asking' | 'net_effective' | 'both'
    concession_text     TEXT,
    available_date      TEXT,
    captured_at         TEXT,
    FOREIGN KEY (building_id) REFERENCES buildings(id)
);
CREATE INDEX IF NOT EXISTS idx_listings_date ON listings(snapshot_date);
CREATE INDEX IF NOT EXISTS idx_listings_bldg ON listings(building_id, snapshot_date);

-- Optional market-level aggregate per date (lets us store survey/market points
-- even when per-unit rows aren't available, e.g. the June 8 seed).
CREATE TABLE IF NOT EXISTS market_history (
    snapshot_date    TEXT PRIMARY KEY,
    total_available  INTEGER,
    by_type_json     TEXT,             -- {"Studio":{"asking":..,"net":..}, ...}
    note             TEXT
);
"""

def conn():
    c = sqlite3.connect(DB_PATH)
    c.row_factory = sqlite3.Row
    c.execute("PRAGMA foreign_keys = ON")
    return c

def init():
    with conn() as c:
        c.executescript(SCHEMA)
    print(f"Initialised {DB_PATH}")

def seed():
    """(Re)load the building dimension by merging the scrape registry with metadata."""
    cfg  = json.load(open(CONFIG_PATH))
    meta = json.load(open(META_PATH))["buildings"]
    now  = datetime.datetime.now().isoformat(timespec="seconds")
    rows = 0
    with conn() as c:
        for b in cfg["buildings"]:
            name = b["building"]
            m = meta.get(name, {})
            slug = m.get("slug") or name.lower().replace(" ", "_")
            c.execute("""
                INSERT INTO buildings (id,name,units,year_built,stories,mgmt,in_market,
                    source_url,method,portal_url,api_endpoint,js_rendered,notes,added_at)
                VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                ON CONFLICT(id) DO UPDATE SET
                    name=excluded.name, units=excluded.units, year_built=excluded.year_built,
                    stories=excluded.stories, mgmt=excluded.mgmt, in_market=excluded.in_market,
                    source_url=excluded.source_url, method=excluded.method,
                    portal_url=excluded.portal_url, api_endpoint=excluded.api_endpoint,
                    js_rendered=excluded.js_rendered, notes=excluded.notes
            """, (slug, name, m.get("units"), m.get("year_built"), m.get("stories"),
                  m.get("mgmt"), 1 if m.get("in_market", True) else 0,
                  b.get("url"), b.get("method"), b.get("portal_url"), b.get("api_endpoint"),
                  1 if b.get("js_rendered") else 0, b.get("notes"), now))
            rows += 1
    print(f"Seeded {rows} buildings.")

# ---- ingest ---------------------------------------------------------------
TYPE_FROM_BEDS = {0: "Studio", 1: "1BR", 2: "2BR", 3: "3BR", 4: "4BR"}

def _slug_for(c, key):
    """Resolve a building key (slug or display name) to a slug."""
    r = c.execute("SELECT id FROM buildings WHERE id=? OR name=?", (key, key)).fetchone()
    return r["id"] if r else None

def ingest_snapshot(units, snapshot_date=None, status_by_building=None):
    """
    Append a dated snapshot.
      units: list of dicts, each with at least {building, ...}. Recognised keys:
        building, unit, unit_type|beds, baths, sqft, asking_rent, net_effective_rent,
        price_basis, concession_text, available_date
      status_by_building: optional {building_key: {units_captured,status,concession_text,concession_pct,message}}
    """
    snapshot_date = snapshot_date or today_et()
    now = datetime.datetime.now().isoformat(timespec="seconds")
    # defense in depth behind the extractor guards: a listing with neither an
    # asking nor a net rent carries no pricing information and is, in practice,
    # extractor junk (413's 2026-06-11 phantom rows). Skip and report.
    pre = len(units)
    units = [u for u in units if u.get("asking_rent") or u.get("net_effective_rent")]
    if len(units) != pre:
        print(f"  ! skipped {pre - len(units)} rent-less unit(s) at ingest")
    inserted, by_b = 0, {}
    store = PS.load(); store_dirty = False; sf_filled = 0   # static physical-attrs merge
    with conn() as c:
        # idempotent re-runs: replace this date's rows ONLY for buildings present in
        # this batch — a building that succeeded in an earlier run today keeps its
        # rows if it fails in a re-run (observed: run #23 erased MetroVue's good
        # capture from run #22 on 2026-06-11).
        batch_slugs = {s for s in (_slug_for(c, u.get("building","")) for u in units) if s}
        if batch_slugs:
            ph = ",".join("?"*len(batch_slugs))
            c.execute(f"DELETE FROM listings WHERE snapshot_date=? AND building_id IN ({ph})",
                      (snapshot_date, *batch_slugs))
        for u in units:
            slug = _slug_for(c, u.get("building", ""))
            if not slug:
                print(f"  ! unknown building '{u.get('building')}' — skipped")
                continue
            # physical attributes are static: fill missing SF from the store, and
            # teach the store any SF the feed DID publish so coverage auto-grows.
            if PS.learn(store, slug, u.get("unit"), u.get("sqft"), u.get("beds"), u.get("baths")):
                store_dirty = True
            if not u.get("sqft"):
                got = PS.sqft_for(store, slug, u.get("unit"))
                if got: u["sqft"] = got; sf_filled += 1
            beds = u.get("beds")
            utype = u.get("unit_type") or TYPE_FROM_BEDS.get(beds)
            c.execute("""INSERT INTO listings (snapshot_date,building_id,unit,unit_type,beds,
                         baths,sqft,asking_rent,net_effective_rent,price_basis,concession_text,
                         available_date,captured_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)""",
                      (snapshot_date, slug, u.get("unit"), utype, beds, u.get("baths"),
                       u.get("sqft"), u.get("asking_rent"), u.get("net_effective_rent"),
                       u.get("price_basis"), u.get("concession_text"),
                       u.get("available_date"), now))
            inserted += 1
            by_b[slug] = by_b.get(slug, 0) + 1
        # write the run-log
        status_by_building = status_by_building or {}
        for slug, cnt in by_b.items():
            st = status_by_building.get(slug, {})
            c.execute("""INSERT INTO snapshots (snapshot_date,building_id,units_captured,status,
                         concession_text,concession_pct,ran_at,message)
                         VALUES (?,?,?,?,?,?,?,?)
                         ON CONFLICT(snapshot_date,building_id) DO UPDATE SET
                            units_captured=excluded.units_captured, status=excluded.status,
                            concession_text=excluded.concession_text,
                            concession_pct=excluded.concession_pct, ran_at=excluded.ran_at""",
                      (snapshot_date, slug, cnt, st.get("status", "working"),
                       st.get("concession_text"), st.get("concession_pct"), now, st.get("message")))
    # append/refresh this date's market-history point so the trend + timeseries grow daily
    with conn() as c:
        _sync_physical_table(c, store)
        tot = _recompute_market_point(c, snapshot_date, "Auto from daily ingest.")
    print(f"Market-history point set for {snapshot_date}: {tot} listings.")
    if store_dirty: PS.save(store)
    if sf_filled or store_dirty:
        print(f"  SF: filled {sf_filled} from store; learned {'yes' if store_dirty else 'none'} new.")
    print(f"Ingested {inserted} units for {snapshot_date} across {len(by_b)} buildings.")
    return inserted

def record_run_log(snapshot_date, rows):
    """Record per-building counts/concessions for a date WITHOUT per-unit rows
    (used to seed the historical June 8 pull whose unit rows live elsewhere)."""
    now = datetime.datetime.now().isoformat(timespec="seconds")
    with conn() as c:
        for r in rows:
            slug = _slug_for(c, r["building"])
            if not slug:
                print(f"  ! unknown building '{r['building']}'"); continue
            c.execute("""INSERT INTO snapshots (snapshot_date,building_id,units_captured,status,
                         concession_text,concession_pct,ran_at,message) VALUES (?,?,?,?,?,?,?,?)
                         ON CONFLICT(snapshot_date,building_id) DO UPDATE SET
                            units_captured=excluded.units_captured, status=excluded.status,
                            concession_text=excluded.concession_text,
                            concession_pct=excluded.concession_pct, ran_at=excluded.ran_at""",
                      (snapshot_date, slug, r.get("units_captured"), r.get("status", "working"),
                       r.get("concession_text"), r.get("concession_pct"), now, r.get("message")))
    print(f"Recorded run-log for {snapshot_date} ({len(rows)} buildings).")

def _recompute_market_point(c, date, note):
    """Quarantine-aware market-history point for one date, on the given connection.
    Single source of truth for the trend total + by-type averages — both ingest and
    clean() call this, so the two paths can never drift. Returns the total counted."""
    ids = set(suspect_listing_ids(c).keys())
    notin = (" AND id NOT IN (" + ",".join("?"*len(ids)) + ")") if ids else ""
    params = (date, *ids)
    tot = c.execute(f"SELECT COUNT(*) FROM listings WHERE snapshot_date=?{notin}", params).fetchone()[0]
    bt = {}
    for r in c.execute(f"""SELECT unit_type t, ROUND(AVG(asking_rent)) a, ROUND(AVG(net_effective_rent)) n
                           FROM listings WHERE snapshot_date=? AND unit_type IS NOT NULL{notin}
                           GROUP BY unit_type""", params):
        bt[r["t"]] = {"asking": r["a"], "net": r["n"]}
    c.execute("""INSERT INTO market_history (snapshot_date,total_available,by_type_json,note)
                 VALUES (?,?,?,?) ON CONFLICT(snapshot_date) DO UPDATE SET
                    total_available=excluded.total_available,
                    by_type_json=excluded.by_type_json, note=excluded.note""",
              (date, tot, json.dumps(bt), note))
    return tot

def set_market_point(snapshot_date, total_available, by_type, note=None):
    with conn() as c:
        c.execute("""INSERT INTO market_history (snapshot_date,total_available,by_type_json,note)
                     VALUES (?,?,?,?) ON CONFLICT(snapshot_date) DO UPDATE SET
                        total_available=excluded.total_available,
                        by_type_json=excluded.by_type_json, note=excluded.note""",
                  (snapshot_date, total_available, json.dumps(by_type), note))
    print(f"Set market point {snapshot_date}: {total_available} available.")

# ---- export ---------------------------------------------------------------
def _sync_physical_table(c, store):
    """Mirror the JSON physical store into a queryable `physical_attributes`
    table (building_id, unit, beds, baths, sqft). The JSON file remains the
    canonical, versioned store; this table is the in-database view of it,
    rebuilt on every sync (idempotent, ~few hundred rows)."""
    c.execute("""CREATE TABLE IF NOT EXISTS physical_attributes (
        building_id TEXT NOT NULL, unit TEXT NOT NULL,
        beds REAL, baths REAL, sqft INTEGER,
        PRIMARY KEY (building_id, unit))""")
    c.execute("DELETE FROM physical_attributes")
    rows = []
    for slug, b in store.get("buildings", {}).items():
        for unit, rec in (b.get("units") or {}).items():
            rows.append((slug, unit, rec.get("beds"), rec.get("baths"), rec.get("sqft")))
    c.executemany("INSERT INTO physical_attributes (building_id,unit,beds,baths,sqft) VALUES (?,?,?,?,?)", rows)
    # plan-level reference SF (e.g. Greyson's RealPage floor plans): kept SEPARATE from
    # per-unit rows so the drill-down / fill-progress stay unit-only, but available to
    # feed type-level SF averages where a building has no per-unit SF source.
    c.execute("""CREATE TABLE IF NOT EXISTS physical_plans (
        building_id TEXT NOT NULL, plan TEXT NOT NULL,
        beds REAL, baths REAL, sqft INTEGER,
        PRIMARY KEY (building_id, plan))""")
    c.execute("DELETE FROM physical_plans")
    prows = []
    for slug, b in store.get("buildings", {}).items():
        for plan, rec in (b.get("plans") or {}).items():
            prows.append((slug, plan, rec.get("beds"), rec.get("baths"), rec.get("sqft")))
    c.executemany("INSERT INTO physical_plans (building_id,plan,beds,baths,sqft) VALUES (?,?,?,?,?)", prows)
    return len(rows)

def _latest_date_per_building(c):
    return {r["building_id"]: r["d"] for r in c.execute(
        "SELECT building_id, MAX(snapshot_date) d FROM snapshots GROUP BY building_id")}

HARD_BAND = (1200, 15000)   # plausible monthly rent range for this market

def suspect_listing_ids(c):
    """Listing ids in the latest snapshots that fail HARD invariants — data the
    pipeline cannot reconcile (net above asking, or rent far outside any
    plausible value). Returns {listing_id: reason}. These units are QUARANTINED:
    excluded from every rent aggregate and reported as errors, so one bad parse
    or a mislabeled price basis can never skew the market numbers."""
    ids = {}
    for r in c.execute("""SELECT l.id, b.name, l.unit, l.asking_rent a, l.net_effective_rent n
                          FROM listings l JOIN buildings b ON b.id=l.building_id
                          JOIN (SELECT building_id bid, MAX(snapshot_date) d FROM snapshots GROUP BY building_id) m
                               ON m.bid=l.building_id AND m.d=l.snapshot_date"""):
        a, n = r["a"], r["n"]
        why = None
        if a and n and n > a * 1.001:
            why = f"net ${n:,.0f} EXCEEDS asking ${a:,.0f} — contradictory (price basis likely mislabeled)"
        elif a and not (HARD_BAND[0] <= a <= HARD_BAND[1]):
            why = f"asking ${a:,.0f} outside plausible band (${HARD_BAND[0]:,}-${HARD_BAND[1]:,}) — parse suspect"
        elif n and not (HARD_BAND[0] <= n <= HARD_BAND[1]):
            why = f"net ${n:,.0f} outside plausible band (${HARD_BAND[0]:,}-${HARD_BAND[1]:,}) — parse suspect"
        if why:
            ids[r["id"]] = f"{r['name']} {r['unit']}: {why}"
    return ids


def validate(c, latest=None):
    """Automated checks on the latest snapshot. Returns (errors, warnings).
    ERRORS  = irreconcilable: quarantined units (excluded from averages) and
              failed scrapes — the dashboard shows these in red.
    WARNINGS = suspicious but usable: wide concession ratios, unit-count drift —
              included in averages, shown in amber for human review."""
    errors = list(suspect_listing_ids(c).values())
    warnings = []
    fut = c.execute("SELECT MAX(snapshot_date) FROM listings").fetchone()[0]
    if fut and fut > today_et():
        errors.append(f"FUTURE-DATED rows present ({fut} > today {today_et()} ET) — clock-bug residue is "
                      f"shadowing fresh data in latest-snapshot lookups; run 'pipeline.py clean' to purge.")
    # staleness: if the newest snapshot is more than 2 days old, the daily scrape
    # is not landing (silent failure / disabled schedule) - surface it on the page
    newest = c.execute("SELECT MAX(snapshot_date) FROM snapshots").fetchone()[0]
    if newest:
        age = (datetime.datetime.now(_ET).date() - datetime.date.fromisoformat(newest)).days
        if age >= 2:
            warnings.append(f"Data is STALE: newest snapshot is {newest} ({age} days old) - the daily scrape has not landed; check the Actions log.")
    # per-building gap: a building with no listings on the global as-of date was
    # silently missed (site unreachable, extractor break, or genuinely zero units)
    gmax = c.execute("SELECT MAX(snapshot_date) FROM listings").fetchone()[0]
    if gmax:
        for r in c.execute("""SELECT b.name nm, MAX(l.snapshot_date) d FROM buildings b
                              LEFT JOIN listings l ON l.building_id=b.id
                              WHERE b.in_market=1 GROUP BY b.id"""):
            if r["d"] != gmax:
                warnings.append(f"{r['nm']}: no listings captured on {gmax} (last seen {r['d'] or 'never'}) — "
                                f"excluded from current averages; site may have been unreachable or empty (check the Actions log).")
    for r in c.execute("""SELECT b.name, l.unit, l.asking_rent a, l.net_effective_rent n
                          FROM listings l JOIN buildings b ON b.id=l.building_id
                          JOIN (SELECT building_id bid, MAX(snapshot_date) d FROM snapshots GROUP BY building_id) m
                               ON m.bid=l.building_id AND m.d=l.snapshot_date"""):
        a, n = r["a"], r["n"]
        if a and n and n <= a * 1.001 and a / n > 1.40:
            warnings.append(f"{r['name']} {r['unit']}: asking/net ratio {a/n:.2f} (> 1.40) — concession term suspect.")
    # unit-count drift vs the building's previous snapshot
    hist = {}
    for r in c.execute("""SELECT b.name nm, s.snapshot_date d, s.units_captured u FROM snapshots s
                          JOIN buildings b ON b.id=s.building_id ORDER BY s.snapshot_date"""):
        hist.setdefault(r["nm"], []).append(r["u"] or 0)
    for nm, seq in hist.items():
        if len(seq) >= 2 and seq[-2] >= 5:
            prev, cur = seq[-2], seq[-1]
            if cur <= prev * 0.4:
                warnings.append(f"{nm}: unit count fell {prev} -> {cur} (>60% drop) — extractor may be partially broken or page changed.")
            elif cur >= prev * 3:
                warnings.append(f"{nm}: unit count jumped {prev} -> {cur} (3x) — selector may be over-matching.")
    # scrape statuses from the latest run: hard failures are errors, skips are warnings
    for r in c.execute("""SELECT b.name nm, s.status, s.message FROM snapshots s
                          JOIN buildings b ON b.id=s.building_id
                          JOIN (SELECT building_id bid, MAX(snapshot_date) d FROM snapshots GROUP BY building_id) m
                               ON m.bid=s.building_id AND m.d=s.snapshot_date
                          WHERE s.status NOT IN ('working','ok','seeded')"""):
        msg = f"{r['nm']}: scrape status '{r['status']}'{(' — ' + r['message'][:120]) if r['message'] else ''}."
        (errors if r["status"] == "error" else warnings).append(msg)
    return errors, warnings


def export(out_path=EXPORT_PATH):
    """Build dashboard_data.json: building set + latest snapshot + history."""
    pstore = PS.load(); sf_src = pstore.get("_meta", {}).get("sf_source", {})
    # static geo reference (address/lat/lng) lives in buildings_meta.json — merged
    # at export so the deployed DB needs no schema change.
    geo = {}
    try:
        with open(paths.config_path("buildings_meta.json")) as f:
            _meta = json.load(f)
            for _n, _m in (_meta.get("buildings") or _meta).items():
                if isinstance(_m, dict) and _m.get("slug") and _m.get("lat") is not None:
                    geo[_m["slug"]] = {"address": _m.get("address"), "lat": _m["lat"], "lng": _m["lng"]}
    except Exception:
        pass
    with conn() as c:
        latest = _latest_date_per_building(c)
        # backfill: learn physical attrs from ALL rows ever ingested — physical
        # facts are immutable, so historical listings (incl. units no longer on
        # the market, or rows ingested before beds/baths learning existed) are
        # valid sources. Rent-less phantom rows are skipped; then refresh the
        # queryable mirror table.
        dirty = False
        for r in c.execute("""SELECT building_id,unit,beds,baths,sqft FROM listings
                              WHERE asking_rent IS NOT NULL OR net_effective_rent IS NOT NULL"""):
            if PS.learn(pstore, r["building_id"], r["unit"], r["sqft"], r["beds"], r["baths"]):
                dirty = True
        if dirty: PS.save(pstore)
        _sync_physical_table(c, pstore)
        quarantine = suspect_listing_ids(c)      # irreconcilable units: excluded from all averages
        qclause = f" AND id NOT IN ({','.join(map(str, quarantine))})" if quarantine else ""
        buildings = []
        for b in c.execute("SELECT * FROM buildings ORDER BY name"):
            d = latest.get(b["id"])
            snap = c.execute("SELECT * FROM snapshots WHERE building_id=? AND snapshot_date=?",
                             (b["id"], d)).fetchone() if d else None
            # per-type rollup from listings at that date (if unit rows exist)
            by_type = {}
            if d:
                for t in c.execute(f"""SELECT unit_type,
                            COUNT(*) n, AVG(asking_rent) ask, AVG(net_effective_rent) net,
                            AVG(sqft) sf, MIN(asking_rent) ask_lo, MAX(asking_rent) ask_hi,
                            MIN(net_effective_rent) net_lo, MAX(net_effective_rent) net_hi,
                            -- $/SF is computed PER UNIT (rent and SF from the SAME unit), then
                            -- averaged — never AVG(rent) over a different pool than AVG(sqft).
                            -- Units missing their own SF are excluded from the $/SF only (they
                            -- still count in rent/sqft averages above). Prevents the single-SF-
                            -- unit pool mismatch (Greyson studio: 5-rent avg / 1-unit SF).
                            AVG(CASE WHEN sqft>0 AND asking_rent IS NOT NULL
                                     THEN asking_rent*12.0/sqft END) ask_psf,
                            AVG(CASE WHEN sqft>0 AND net_effective_rent IS NOT NULL
                                     THEN net_effective_rent*12.0/sqft END) net_psf,
                            SUM(CASE WHEN sqft>0 AND (asking_rent IS NOT NULL OR net_effective_rent IS NOT NULL)
                                     THEN 1 ELSE 0 END) psf_n
                            FROM listings
                            WHERE building_id=? AND snapshot_date=?{qclause} GROUP BY unit_type""",
                            (b["id"], d)):
                    if t["unit_type"]:
                        by_type[t["unit_type"]] = {
                            "count": t["n"],
                            "asking_avg": round(t["ask"]) if t["ask"] else None,
                            "net_avg": round(t["net"]) if t["net"] else None,
                            "sqft_avg": round(t["sf"]) if t["sf"] else None,
                            "asking_min": round(t["ask_lo"]) if t["ask_lo"] else None,
                            "asking_max": round(t["ask_hi"]) if t["ask_hi"] else None,
                            "net_min": round(t["net_lo"]) if t["net_lo"] else None,
                            "net_max": round(t["net_hi"]) if t["net_hi"] else None,
                            # per-unit $/SF (same-unit rent÷SF, averaged); null unless ≥1 unit
                            # has both. psf_n = how many units backed it (honesty signal).
                            "asking_psf": round(t["ask_psf"], 2) if t["ask_psf"] else None,
                            "net_psf": round(t["net_psf"], 2) if t["net_psf"] else None,
                            "psf_n": t["psf_n"] or 0}
            # concession provenance: read-from-site today > derived-from-unit-pricing.
            # No stale carry-forward — the building pages are the source of truth.
            conc_dv = None
            if d:
                r2 = c.execute(f"""SELECT AVG(1.0-net_effective_rent*1.0/asking_rent) pu, COUNT(*) n
                                   FROM listings WHERE building_id=? AND snapshot_date=?{qclause}
                                   AND asking_rent IS NOT NULL AND net_effective_rent IS NOT NULL
                                   AND net_effective_rent < asking_rent""", (b["id"], d)).fetchone()
                if r2 and r2["n"]:
                    conc_dv = round(r2["pu"], 4)
                # NO building-level fallback: comparing AVG(ask) of some units to
                # AVG(net) of *different* units manufactures a fake discount
                # (Urby showed a 27.9% "concession" purely from pool mismatch).
                # Derived requires gross AND net on the SAME unit.
            # physical-attributes completeness tracker: how many of this building's
            # units have SF recorded, and whether it can ever be fully recorded.
            pb = pstore.get("buildings", {}).get(b["id"], {})
            phys_recorded = sum(1 for u in (pb.get("units") or {}).values() if u.get("sqft"))
            phys_modeled = bool(pb.get("line_pattern"))
            phys_lines = len(pb.get("lines", {}))
            phys_plans = len(pb.get("plans", {}))
            phys_source = sf_src.get(b["id"], "unknown")
            g = geo.get(b["id"], {})
            buildings.append({
                "id": b["id"], "name": b["name"], "units": b["units"],
                "address": g.get("address"), "lat": g.get("lat"), "lng": g.get("lng"),
                "phys_recorded": phys_recorded, "phys_modeled": phys_modeled,
                "phys_lines": phys_lines, "phys_plans": phys_plans, "phys_source": phys_source,
                "year_built": b["year_built"], "stories": b["stories"], "mgmt": b["mgmt"],
                "in_market": bool(b["in_market"]), "method": b["method"],
                "source_url": b["source_url"], "portal_url": b["portal_url"],
                "available_now": snap["units_captured"] if snap else None,
                "concession_text": snap["concession_text"] if snap else None,
                "concession_pct": snap["concession_pct"] if snap else None,
                "conc_derived_pct": conc_dv,
                "as_of": d, "by_type": by_type or None})
        history = [{"date": r["snapshot_date"], "total_available": r["total_available"],
                    "by_type": json.loads(r["by_type_json"]) if r["by_type_json"] else None,
                    "note": r["note"]}
                   for r in c.execute("SELECT * FROM market_history ORDER BY snapshot_date")]
        for h in history:   # all-types composite straight from that date's listings
            r = c.execute("SELECT ROUND(AVG(asking_rent)) a, ROUND(AVG(net_effective_rent)) n FROM listings WHERE snapshot_date=?", (h["date"],)).fetchone()
            h["all_asking"], h["all_net"] = r["a"], r["n"]
        as_of = max([d for d in latest.values() if d], default=None)
        # per-building bedroom census (reference table; drives the dashboard's by-building view)
        unit_mix = []
        try:
            for r in c.execute("SELECT * FROM unit_mix ORDER BY is_sourced DESC, total DESC"):
                unit_mix.append({k: r[k] for k in r.keys()})
        except sqlite3.OperationalError:
            pass
        # average recorded unit size by bedroom type, from the physical_attributes
        # mirror table (SF-bearing records only). Real collected data — accrues as
        # units list; a type with no SF yet is simply omitted.
        avg_sf = []
        try:
            for r in c.execute("""WITH src AS (
                                      SELECT beds, sqft FROM physical_attributes
                                        WHERE sqft IS NOT NULL AND beds IS NOT NULL
                                      UNION ALL
                                      SELECT pp.beds, pp.sqft FROM physical_plans pp
                                        WHERE pp.sqft IS NOT NULL AND pp.beds IS NOT NULL
                                          AND pp.building_id NOT IN (
                                            SELECT DISTINCT building_id FROM physical_attributes
                                              WHERE sqft IS NOT NULL)
                                    )
                                    SELECT CASE WHEN beds=0 THEN 'Studio' WHEN beds=1 THEN '1BR'
                                                WHEN beds=2 THEN '2BR' WHEN beds>=3 THEN '3BR' END AS t,
                                           COUNT(*) n, ROUND(AVG(sqft)) avg_sqft,
                                           MIN(sqft) min_sqft, MAX(sqft) max_sqft
                                    FROM src
                                    GROUP BY t HAVING t IS NOT NULL
                                    ORDER BY MIN(beds)"""):
                avg_sf.append({k: r[k] for k in r.keys()})
        except sqlite3.OperationalError:
            pass
        dq_errors, dq_warnings = validate(c)
    payload = {"generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
               "as_of": as_of, "buildings": buildings, "market_history": history,
               "unit_mix": unit_mix, "avg_unit_sf": avg_sf,
               "data_quality": {"checked_at": datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds"),
                                 "errors": dq_errors, "warnings": dq_warnings,
                                 "quarantined_units": len(quarantine),
                                 "policy": "Units failing hard invariants (net > asking, implausible rents) are excluded from every average and listed as errors."}}
    ref_path = paths.config_path("reference.json")           # static workbook blocks
    if os.path.exists(ref_path):
        ref = json.load(open(ref_path))
        ref.pop("_comment", None)
        payload["reference"] = ref
    json.dump(payload, open(out_path, "w"), indent=2)
    print(f"Exported {out_path} ({len(buildings)} buildings, {len(history)} history points).")
    return payload

def status():
    with conn() as c:
        nb = c.execute("SELECT COUNT(*) n FROM buildings").fetchone()["n"]
        nl = c.execute("SELECT COUNT(*) n FROM listings").fetchone()["n"]
        dates = [r["snapshot_date"] for r in c.execute(
            "SELECT DISTINCT snapshot_date FROM snapshots ORDER BY snapshot_date")]
        print(f"Buildings: {nb} | Listing rows: {nl} | Snapshot dates: {dates}")
        for b in c.execute("""SELECT b.name, s.snapshot_date, s.units_captured, s.concession_text
                              FROM buildings b LEFT JOIN snapshots s ON s.building_id=b.id
                              AND s.snapshot_date=(SELECT MAX(snapshot_date) FROM snapshots
                              WHERE building_id=b.id) ORDER BY s.units_captured DESC NULLS LAST"""):
            print(f"  {b['name']:<26} {str(b['units_captured'] or '-'):>4} avail"
                  f"   {b['snapshot_date'] or '(no pull)'}   {b['concession_text'] or ''}")


def clean():
    """Sweep bad rows left by bad pulls: (1) purge rows stamped with an
    IMPOSSIBLE FUTURE date — residue of the pre-ET UTC clock bug, whose ghost
    snapshots shadow fresh data in every MAX(snapshot_date) lookup (observed:
    run #27's '2026-06-12' rows hid run #28's corrected 06-11 rows, so the
    dashboard showed pre-SF-store data); (2) delete listings with neither an
    asking nor a net rent (extractor junk); then sync snapshots.units_captured
    and recompute market_history for every affected date.
    Idempotent — safe to run every day; reports what it removed."""
    removed_future = 0
    with conn() as c:
        today = today_et()
        fut = [r[0] for r in c.execute(
            "SELECT DISTINCT snapshot_date FROM listings WHERE snapshot_date > ? "
            "UNION SELECT DISTINCT snapshot_date FROM snapshots WHERE snapshot_date > ?",
            (today, today))]
        for d in sorted(fut):
            n = c.execute("SELECT COUNT(*) FROM listings WHERE snapshot_date=?", (d,)).fetchone()[0]
            print(f"clean: PURGING future-dated snapshot {d} ({n} listings) — UTC clock-bug residue; today (ET) is {today}.")
            c.execute("DELETE FROM listings WHERE snapshot_date=?", (d,))
            c.execute("DELETE FROM snapshots WHERE snapshot_date=?", (d,))
            c.execute("DELETE FROM market_history WHERE snapshot_date=?", (d,))
            removed_future += n
    with conn() as c:
        bad = c.execute("""SELECT id, building_id, snapshot_date, unit FROM listings
                           WHERE asking_rent IS NULL AND net_effective_rent IS NULL""").fetchall()
        if not bad:
            print(f"clean: nothing else to remove." if removed_future else "clean: nothing to remove.")
            return removed_future
        dates = sorted({r["snapshot_date"] for r in bad})
        pairs = sorted({(r["building_id"], r["snapshot_date"]) for r in bad})
        for r in bad:
            print(f"clean: removing {r['building_id']} {r['snapshot_date']} unit {r['unit']} (no rents)")
        c.execute("""DELETE FROM listings
                     WHERE asking_rent IS NULL AND net_effective_rent IS NULL""")
        for bid, d in pairs:   # snapshot counts reflect reality after the sweep
            n = c.execute("SELECT COUNT(*) FROM listings WHERE building_id=? AND snapshot_date=?",
                          (bid, d)).fetchone()[0]
            c.execute("UPDATE snapshots SET units_captured=? WHERE building_id=? AND snapshot_date=?",
                      (n, bid, d))
        for d in dates:        # recompute the trend point for each touched date
            _recompute_market_point(c, d, "Recomputed by clean().")
    print(f"clean: removed {len(bad)} row(s) across {len(pairs)} building-date(s); "
          f"market_history recomputed for {dates}.")
    return len(bad) + removed_future

if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "status"
    if cmd == "init": init()
    elif cmd == "seed": seed()
    elif cmd == "ingest":
        data = json.load(open(sys.argv[2]))
        units = data["units"] if isinstance(data, dict) and "units" in data else data
        ingest_snapshot(units, data.get("snapshot_date") if isinstance(data, dict) else None)
    elif cmd == "export": export()
    elif cmd == "clean": clean()
    elif cmd == "status": status()
    else: print(__doc__)
